---
- name: Register Host With XI
  uri:
    url: http://{{ xi_ip }}/nagiosxi/api/v1/config/host?apikey={{ xi_api_key }}
    body: 'host_name={{ ansible_hostname|upper }}&address={{ ansible_default_ipv4.address }}&check_command=check_ping\!3000,80%\!5000,100%&max_check_attempts=2&check_period=24x7&contacts=nagiosadmin&notification_interval=5&notification_period=24x7'
    method: POST
    validate_certs: no
    timeout: 120
