---
- name: Install NCPA and Register Host and Services
  hosts: all
  remote_user: root

  vars_files:
    - 'secrets.yml'
  vars:
    xi_ip: 'lbwkbsvmnxi01.wikilabs.lab'

  roles:
    - role: ncpa_install_linux
    - role: register_with_xi
